import type { EcosystemSnapshot } from '@/lib/snapshot';

const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
const usd = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 2,
});

export function snapshotToMarkdown(snapshot: EcosystemSnapshot) {
  const { network, economy } = snapshot;
  const sourceRows = snapshot.sources
    .map((source) => `| ${source.name} | ${source.state} | ${source.cadence} | ${source.url} |`)
    .join('\n');
  const signalRows = snapshot.signals
    .map((signal) => `- **${signal.severity.toUpperCase()} — ${signal.title}:** ${signal.detail}`)
    .join('\n');

  return `# SOL//PULSE — Solana Ecosystem Report

Generated: ${snapshot.generatedAt}  
Data state: ${snapshot.state}

## Briefing

${snapshot.briefing}

## Network

| Metric | Value |
| --- | ---: |
| TPS | ${number.format(network.tps)} |
| Median slot time | ${number.format(network.slotTimeMs)} ms |
| Block height | ${number.format(network.blockHeight)} |
| Epoch | ${network.epoch} (${number.format(network.epochProgress)}%) |
| Active validators | ${number.format(network.activeValidators)} |
| Delinquent validators | ${number.format(network.delinquentValidators)} (${number.format(network.delinquentPercent)}%) |
| SOL supply | ${number.format(network.supplySol)} |

## Economy

| Metric | Value |
| --- | ---: |
| SOL price | ${usd.format(economy.solPrice)} (${number.format(economy.solPriceChange24h)}% 24h) |
| Solana DeFi TVL | ${usd.format(economy.tvl)} |
| TVL change | ${number.format(economy.tvlChange1d)}% 1d / ${number.format(economy.tvlChange7d)}% 7d / ${number.format(economy.tvlChange30d)}% 30d |
| DEX volume | ${usd.format(economy.dexVolume24h)} 24h / ${usd.format(economy.dexVolume7d)} 7d |
| Stablecoin supply | ${usd.format(economy.stablecoinSupply)} |

## Signals

${signalRows}

## Data sources

| Source | State | Refresh | URL |
| --- | --- | --- | --- |
${sourceRows}

---

Generated by SOL//PULSE. Values are informational and may lag their upstream sources.
`;
}
