import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const baseUrl = process.env.SOL_PULSE_URL ?? 'http://localhost:3000';
const reportDirectory = fileURLToPath(new URL('../reports/', import.meta.url));

const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
const usd = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 2,
});

function toMarkdown(snapshot) {
  const { network, economy } = snapshot;
  const signals = snapshot.signals.map(
    (signal) => '- **' + signal.severity.toUpperCase() + ' — ' + signal.title + ':** ' + signal.detail,
  );
  const sources = snapshot.sources.map(
    (source) => '| ' + source.name + ' | ' + source.state + ' | ' + source.cadence + ' | ' + source.url + ' |',
  );

  return [
    '# SOL//PULSE — Solana Ecosystem Report',
    '',
    'Generated: ' + snapshot.generatedAt,
    'Data state: ' + snapshot.state,
    '',
    '## Briefing',
    '',
    snapshot.briefing,
    '',
    '## Network',
    '',
    '| Metric | Value |',
    '| --- | ---: |',
    '| TPS | ' + number.format(network.tps) + ' |',
    '| Median slot time | ' + number.format(network.slotTimeMs) + ' ms |',
    '| Block height | ' + number.format(network.blockHeight) + ' |',
    '| Epoch | ' + network.epoch + ' (' + number.format(network.epochProgress) + '%) |',
    '| Active validators | ' + number.format(network.activeValidators) + ' |',
    '| Delinquent validators | ' + number.format(network.delinquentValidators) + ' (' + number.format(network.delinquentPercent) + '%) |',
    '| SOL supply | ' + number.format(network.supplySol) + ' |',
    '',
    '## Economy',
    '',
    '| Metric | Value |',
    '| --- | ---: |',
    '| SOL price | ' + usd.format(economy.solPrice) + ' (' + number.format(economy.solPriceChange24h) + '% 24h) |',
    '| Solana DeFi TVL | ' + usd.format(economy.tvl) + ' |',
    '| TVL change | ' + number.format(economy.tvlChange1d) + '% 1d / ' + number.format(economy.tvlChange7d) + '% 7d / ' + number.format(economy.tvlChange30d) + '% 30d |',
    '| DEX volume | ' + usd.format(economy.dexVolume24h) + ' 24h / ' + usd.format(economy.dexVolume7d) + ' 7d |',
    '| Stablecoin supply | ' + usd.format(economy.stablecoinSupply) + ' |',
    '',
    '## Signals',
    '',
    ...signals,
    '',
    '## Data sources',
    '',
    '| Source | State | Refresh | URL |',
    '| --- | --- | --- | --- |',
    ...sources,
    '',
    '---',
    '',
    'Generated by SOL//PULSE. Values are informational and may lag their upstream sources.',
    '',
  ].join('\n');
}

const response = await fetch(baseUrl + '/api/snapshot', { signal: AbortSignal.timeout(20_000) });
if (!response.ok) throw new Error('Snapshot request failed (' + response.status + ')');

const snapshot = await response.json();
await mkdir(reportDirectory, { recursive: true });
await Promise.all([
  writeFile(reportDirectory + 'latest.json', JSON.stringify(snapshot, null, 2) + '\n', 'utf8'),
  writeFile(reportDirectory + 'latest.md', toMarkdown(snapshot), 'utf8'),
]);

console.log('Captured live reports from ' + baseUrl + ' into reports/latest.json and reports/latest.md');
